### ISSUE TITLE
error: permission denied for function postgis_type_name

### ISSUE THREAD

**Issue by cellis** [graphile/postgis#28]
I'm getting an error with this extension when running a basic query:

```graphql
query findPosts {
	allPosts(first:1){
    nodes {
      point {
      	x
        y
      }
    }
  }
}
```

```sh
error: permission denied for function postgis_type_name
```

For background, the table I'm attempting to query looks like this:

```
CREATE TABLE myschema.post (
    ...
    point myschema_gis.geometry(Point,4326),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);

```

Note this happens when I replace `myschema_gis` with `public`.

I'm pretty sure it's because the `postgis` extension is installed in the `public` schema, but that schema has `alter default privileges revoke execute on functions from public;` per the [tutorial](https://github.com/graphile/postgraphile/blob/master/examples/forum/TUTORIAL.md). Any ideas how to get around this? I tried to install into a clean SCHEMA (`myschema_gis`) and grant execute on all functions in `myschema_gis` but 1) that didn't work because of what I assume to be this line: https://github.com/graphile/postgis/blob/master/src/PostgisRegisterTypesPlugin.ts#L193. And 2) It would be probably be a security vulnerability.

Thanks for your time and making this plugin!

**Comment by benjie** [comment]
Hey Cameron; long time no speak! Sorry it's taken me a few days to reply, it's been hectic!

I'm not sure how much value

```
alter default privileges revoke execute on functions from public;
```

really gives. I added it at the suggestion of another developer, but TBH I always want to grant execute on functions in my GraphQL schema, that's why I add them there. Personally I'd probably just undo this.

Assuming you want to stick with the `default privileges revoke`, the solution is to grant access to the relevant postgis functions. Installing PostGIS to an alternative schema _should_ work - make sure you restart PostGraphile - let me know what error you faced there and maybe I can shed some light. Failing that, granting on all functions in public should also work (assuming there's no functions you don't want to grant access to).

**Comment by cellis** [comment]
Hey @benjie i realized the postgis extension works and  ‘my_gis_schema’ also works. What didn’t work was trying to make a mutation on a geometry ( vs geography ), then I read that there is read only support for geometry types and it made sense 😀. So I just created a custom function for create post! Thanks again, hope all is well!

**Comment by cellis** [comment]
The only thing I had to remember is to access all postgis functions fully qualified by schema (e.g. my_schema_gis.st_makepoint )

**Comment by benjie** [comment]
:+1: Glad you got it sorted :grin: All's good, just hella busy!
